@startuml

skin rose
hide empty members
left to right direction

skinparam  {
    defaultFontSize             16
    shadowing                   true
    RoundCorner                 10
    packageBackgroundColor      LightGoldenRodYellow
    ' topPadding                  20
    'backgroundColor             transparent
    'handwritten                 true
    'change to 150 to increase the quality of the image
    ' dpi                         120
}

' TODO: (durrutia) rename all to english

package roger {

    package "Usuarios" {

        entity Persona {
            * RUT/Pasaporte
            * Nombres
            * Apellidos
            * Correo Electrónico
            * Celular
            * Nacionalidad
            * Género
            ..
            * Login
            * Contraseña
            * Fecha de Creación
            * Fecha de Caducidad
            * Activa
        }

        ' Etiqueta: lugar, valor: Santiago
        ' Etiqueta: color, valor: RBG
        ' Etiqueta: estado, valor: algo
        ' Etiqueta: observacion, valor: ...
        ' Etiqueta: numero_autor, valor:
        ' Etiqueta: tituto_autor, valor: santiago



        enum Rol {
            * Administrador
            * Curador/Experto
            * Usuario
            * Mesa Evaluadora
            * Investigador
            * Digitalizador
        }
        Rol "1..*" <-- Persona : < tiene roles

    }

    package "Recursos Digitales" {

        entity "Colección" as Coleccion {
            * Nombre
            * Descripción
            * Fecha de Creación
        }

        ' @see https://schema.org/ImageObject
        entity Imagen {
            * Key: ULID
            * Nombre del Archivo
            * Identificador [Carolina Castañeda]
            * Identificación Localización Física Original
            * Fecha de Digitalización
            * Internal Cronology
            ..
            * Alto Pixeles
            * Ancho Pixeles
            * Profundidad de Color
            * Resolution [ESO?]
            ..
            * Licencia
            * Derechos de Autor/Uso
        }
        Imagen "*" <-- Persona : < responsable
        Imagen "*" <-- Persona : < digitalizado por
        Imagen "1..*" <-- "Coleccion": < pertenece a

        enum TipoImagen {
            * CR3 [master]
            * TIFF
            * JPG
            * PNG
        }
        TipoImagen "1..*" <-- Imagen : < es de tipo

        entity Metadato {
            * Etiqueta
            * Valor
        }
        Metadato "1..*" <-- Imagen : < tiene

        entity Dimension {
            * Subject Detection
            * Object Detection
            * Geolocalization
            * Temporality
            * Cronology
        }
        ' Dimension "0..*" <-- Imagen : < had
        ' TODO: add date, model, person, etc.

        ' https://iiif.io/

        ' Dimensions:
        ' 1. Subject detection.
        ' 2. Object detection.
        ' 3. Geolocalization: Berlin.
        ' 4. Temporality: August 13th 1962 14:15 hrs.
        ' 5. Internal cronology: Where is located the image in a serie?
    }

    package "Research" {

        entity Proyecto {
            * Nombre
            * Descripción
            * Fecha de Inicio
            * Fecha de Término
        }
        Proyecto "*" <-- Persona : < es responsable
        Proyecto --> "*" Coleccion: > utiliza
        Proyecto --> "*" Imagen: > utiliza

        entity Experiment {
            * Description
            * Date
        }
        Experiment --> "1" Imagen
        Experiment --> "1" Dimension
        Experiment --> "1" Persona
        Experiment --> "*" Metadato

    }

}

@enduml
